### ISSUE TITLE
imsrybr0 - Pagination is wrong in GetIdsOfActiveTopics

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-allora-judging#115]
imsrybr0

High

# Pagination is wrong in GetIdsOfActiveTopics

## Note
I did not find this issue on my own, I only saw it being fixed on the main repository in this [PR](https://github.com/allora-network/allora-chain/pull/406).

## Summary
Pagination is wrong in `GetIdsOfActiveTopics`

## Vulnerability Detail
`GetIdsOfActiveTopics` assumes that IDs of active topics are sequential, however that is not the case.

## PoC 1
This creates 10000 and activates 200 of them, then tries to get all IDs active topics.
Instead of returning all the 200 active IDs, it will stop at the active topic with an ID of 200 and only return 4 active IDs for the first page.

```golang
func (s *KeeperTestSuite) TestGetActiveTopics() {
	ctx := s.ctx
	keeper := s.emissionsKeeper

	count := uint64(0)
	for i := 1; i <= 10000; i++ {
		topic := types.Topic{Id: uint64(i)}
		keeper.SetTopic(ctx, topic.Id, topic)

		if i%50 == 0 {
			keeper.ActivateTopic(ctx, topic.Id)
			count++
		}
	}

	// Fetch only active topics
	pagination := &types.SimpleCursorPaginationRequest{
		Key:   nil,
		Limit: count,
	}

	activeTopics, _, err := keeper.GetIdsOfActiveTopics(ctx, pagination)

	s.Require().NoError(err, "Fetching active topics should not produce an error")

	s.Require().Equal(int64(count), len(activeTopics), fmt.Sprintf("Should retrieve exactly %d active topics", count))
}
```

```console
=== RUN   TestKeeperTestSuite/TestGetActiveTopics
    keeper_test.go:1955:
        	Error Trace:	allora-chain/x/emissions/keeper/keeper_test.go:1955
        	Error:      	Not equal:
        	            	expected: int64(200)
        	            	actual  : int(4)
        	Test:       	TestKeeperTestSuite/TestGetActiveTopics
        	Messages:   	Should retrieve exactly 200 active topics
```

## POC 2
This creates 200 topics and only activates the ones with IDs above 100 then tries to get the first 100 active topics.

Instead of returning a result with IDs above 100, it returns nothing.

This impacts [topic rewards](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/module/rewards/topic_rewards.go#L65) as no active topics will be processed (.e.g : no topic fee revenue drip) if there is no active token ID below the `DefaultPageLimit`(100 by default).

```golang
func (s *KeeperTestSuite) TestGetActiveTopics() {
	ctx := s.ctx
	keeper := s.emissionsKeeper

	for i := 1; i <= 200; i++ {
		topic := types.Topic{Id: uint64(i)}
		keeper.SetTopic(ctx, topic.Id, topic)

		if i > 100 {
			keeper.ActivateTopic(ctx, topic.Id)
		}
	}

	// Fetch only active topics
	pagination := &types.SimpleCursorPaginationRequest{
		Key:   nil,
		Limit: 100,
	}

	activeTopics, _, err := keeper.GetIdsOfActiveTopics(ctx, pagination)

	s.Require().NotNil(activeTopics)

	s.Require().NoError(err, "Fetching active topics should not produce an error")

	s.Require().Equal(100, len(activeTopics), fmt.Sprintf("Should retrieve exactly 100 active topics"))
}
```

```console
=== RUN   TestKeeperTestSuite/TestGetActiveTopics
    keeper_test.go:1923:
        	Error Trace:	allora-chain/x/emissions/keeper/keeper_test.go:1923
        	Error:      	Expected value not to be nil.
        	Test:       	TestKeeperTestSuite/TestGetActiveTopics
--- FAIL: TestKeeperTestSuite (0.05s)
```

## Impact
* Forces to use multiple queries to get the desired amount of active ids (.e.g: in PoC 1, if you need the full 100 active topics, and you can only get 4 per page, you'll need to query more pages to get your desired result)
* No active topics will be processed for topic rewards if there are no active topics with an ID below the `DefaultPageLimit`

## Code Snippet
[GetIdsOfActiveTopics](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/keeper.go#L1605-L1634)
```golang
func (k Keeper) GetIdsOfActiveTopics(ctx context.Context, pagination *types.SimpleCursorPaginationRequest) ([]TopicId, *types.SimpleCursorPaginationResponse, error) {
	limit, start, err := k.CalcAppropriatePaginationForUint64Cursor(ctx, pagination)
	if err != nil {
		return nil, nil, err
	}

	startKey := make([]byte, binary.MaxVarintLen64)
	binary.BigEndian.PutUint64(startKey, start)
	nextKey := make([]byte, binary.MaxVarintLen64)
	binary.BigEndian.PutUint64(nextKey, start+limit)

	rng, err := k.activeTopics.IterateRaw(ctx, startKey, nextKey, collections.OrderAscending) // <==== Audit : This assumes that there are {limit} number of active topics with consecutive IDs betwen {start} and {start+limit}
	if err != nil {
		return nil, nil, err
	}
	activeTopics, err := rng.Keys()
	if err != nil {
		return nil, nil, err
	}
	defer rng.Close()

	// If there are no topics, we return the nil for next key
	if activeTopics == nil {
		nextKey = make([]byte, 0)
	}

	return activeTopics, &types.SimpleCursorPaginationResponse{
		NextKey: nextKey,
	}, nil
}
```

[SafeApplyFuncOnAllActiveEpochEndingTopics](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/module/rewards/topic_rewards.go#L53-L96)
```golang
func SafeApplyFuncOnAllActiveEpochEndingTopics(
	ctx sdk.Context,
	k keeper.Keeper,
	block BlockHeight,
	fn func(sdkCtx sdk.Context, topic *types.Topic) error,
	topicPageLimit uint64,
	maxTopicPages uint64,
) error {
	topicPageKey := make([]byte, 0)
	i := uint64(0)
	for {
		topicPageRequest := &types.SimpleCursorPaginationRequest{Limit: topicPageLimit, Key: topicPageKey}
		topicsActive, topicPageResponse, err := k.GetIdsOfActiveTopics(ctx, topicPageRequest) // <==== Audit
		if err != nil {
			Logger(ctx).Warn(fmt.Sprintf("Error getting ids of active topics: %s", err.Error()))
			continue
		}

		for _, topicId := range topicsActive {
			topic, err := k.GetTopic(ctx, topicId)
			if err != nil {
				Logger(ctx).Warn(fmt.Sprintf("Error getting topic: %s", err.Error()))
				continue
			}

			if k.CheckCadence(block, topic) {
				// All checks passed => Apply function on the topic
				err = fn(ctx, &topic)
				if err != nil {
					Logger(ctx).Warn(fmt.Sprintf("Error applying function on topic: %s", err.Error()))
					continue
				}
			}
		}

		// if pageResponse.NextKey is empty then we have reached the end of the list
		if topicsActive == nil || i > maxTopicPages { // <==== Audit : If all active topics IDs are above {topicPageLimit}, topicsActive == nil will be satisfied here as shown in PoC2
			break
		}
		topicPageKey = topicPageResponse.NextKey
		i++
	}
	return nil
}
```
## Tool used
Manual Review

## Recommendation
Use regular Iterator to iterate over active topic IDs and build the result and stop whenever the limit is reached.

Duplicate of #91

**Comment by imsrybr0** [comment]
Escalate

I believe this covers both #60 (check PoC 1) and #91 (check PoC 2).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I believe this covers both #60 (check PoC 1) and #91 (check PoC 2).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
> Escalate
> 
> I believe this covers both #60 (check PoC 1) and #91 (check PoC 2).

It appears both 60 & 91 are covered by this report. but this report was not separated into two issues.

**Comment by imsrybr0** [comment]
Hi @mystery0x, both have the same root cause.

**Comment by WangSecurity** [comment]
@mystery0x it seems that #60 and #91 are the same root cause? In both, the IDs stop retrieving when they don't return the consecutive value. It's just #60 showing that it will return 0 if the first value is not 0, i.e. the same as the scenario in #91 if the active IDs are 2 and 3 instead of 1 and 3. Is it correct, or am I missing something?

**Comment by mystery0x** [comment]
@WangSecurity yes, both 60 and 91 do indeed appear to have the same root cause.

**Comment by WangSecurity** [comment]
Sounds good, planning to accept the escalation and duplicate #91 with #60, since #91 is more of an edge case with 0 value.

**Comment by zhaojio** [comment]
> Sounds good, planning to accept the escalation and duplicate #91 with #60, since #91 is more of an edge case with 0 value.

#91 is not duplicate with #60, #60 and other reports do not describe attack by attacker, their impact is different.

**Comment by WangSecurity** [comment]
But the root cause is the same. The impact being different is common if the attack path is different, but the main thing is that the root cause of the 2 issues is the same. Hence, the decision remains the same, planning to accept the escalation and duplicate #91 with #60.

**Comment by zhaojio** [comment]
> But the root cause is the same. The impact being different is common if the attack path is different, but the main thing is that the root cause of the 2 issues is the same. Hence, the decision remains the same, planning to accept the escalation and duplicate #91 with #60.

The root cause is not same:
#91 contains another issue,

```go
	// If there are no topics, we return the nil for next key
	if activeTopics == nil {
		nextKey = make([]byte, 0)
	}
	return activeTopics, &types.SimpleCursorPaginationResponse{
		NextKey: nextKey,
	}, nil
```

When `activeTopics` is empty it causes `nextKey` to start at 0, `SafeApplyFuncOnAllActiveEpochEndingTopics` function through `nextKey` is needed to deal with the rest of the page.

**Comment by WangSecurity** [comment]
As I understand the problem is the same:
The function GetIdsOfActiveTopics assumes that all topic ids are consecutive and breaks when there's no topic with the appropriate ID.

Report #60 shows a case when there are topics with ID 1 and 3 and the function returns only 1 active ID instead of both 1 and 3 because the function expects them to be consecutive.

Issue #91 shows an edge case when the very first ID is not active, resulting in the function returning 0. The reason is that it expects consecutive ids and stops when the next consecutive number is inactive. Here, if the very first id is inactive, that's why the function returns 0.

If my understanding above is incorrect, please correct me, but I believe both issues come from the same problem. The decision remains the same, planning to accept the escalation and duplicate #91 with #60

**Comment by zhaojio** [comment]
> As I understand the problem is the same: The function GetIdsOfActiveTopics assumes that all topic ids are consecutive and breaks when there's no topic with the appropriate ID.
> 
> Report #60 shows a case when there are topics with ID 1 and 3 and the function returns only 1 active ID instead of both 1 and 3 because the function expects them to be consecutive.
> 
> Issue #91 shows an edge case when the very first ID is not active, resulting in the function returning 0. The reason is that it expects consecutive ids and stops when the next consecutive number is inactive. Here, if the very first id is inactive, that's why the function returns 0.
> 
> If my understanding above is incorrect, please correct me, but I believe both issues come from the same problem. The decision remains the same, planning to accept the escalation and duplicate #91 with #60

both issues are caused by map traversal problems, but map traversal can cause many problems, can not say that they are all the same problem,
The problem in #60 is that the map returns incomplete data.
The problem in #91 is that map returns empty data.
For example, mathematical operations can cause a lot of problems, if there are 2 cases, one is to return 0, the other is to return negative, causing different effects, why are they the same problem?

**Comment by WangSecurity** [comment]
> both issues are caused by map traversal problems, but map traversal can cause many problems, can not say that they are all the same problem

But if the 2 issues happen by the same root cause, they must be duplicated. Having different paths and impacts while having the same root cause is normal. Still, it doesn't mean the issues are different.

> The problem in https://github.com/sherlock-audit/2024-06-allora-judging/issues/60 is that the map returns incomplete data.
The problem in https://github.com/sherlock-audit/2024-06-allora-judging/issues/91 is that map returns empty data

I believe that's the impact, not the root cause.

> For example, mathematical operations can cause a lot of problems, if there are 2 cases, one is to return 0, the other is to return negative, causing different effects, why are they the same problem

The same as above applies, the duplication is not based on the impact, it's based on the root cause. The comment above doesn't show that the 2 issues have a different root cause. Hence, I still stand by my decision that the two reports have the same root cause, only 2 different attack paths and impacts. Thus, they should be considered duplicates.

The decision remains, planning to accept the escalation and duplicate #91 with #60.

**Comment by zhaojio** [comment]
> > both issues are caused by map traversal problems, but map traversal can cause many problems, can not say that they are all the same problem
> 
> But if the 2 issues happen by the same root cause, they must be duplicated. Having different paths and impacts while having the same root cause is normal. Still, it doesn't mean the issues are different.
> 
> > The problem in https://github.com/sherlock-audit/2024-06-allora-judging/issues/60 is that the map returns incomplete data.
> The problem in https://github.com/sherlock-audit/2024-06-allora-judging/issues/91 is that map returns empty data
> 
> I believe that's the impact, not the root cause.
> 
> > For example, mathematical operations can cause a lot of problems, if there are 2 cases, one is to return 0, the other is to return negative, causing different effects, why are they the same problem
> 
> The same as above applies, the duplication is not based on the impact, it's based on the root cause. The comment above doesn't show that the 2 issues have a different root cause. Hence, I still stand by my decision that the two reports have the same root cause, only 2 different attack paths and impacts. Thus, they should be considered duplicates.
> 
> The decision remains, planning to accept the escalation and duplicate #91 with #60.

How do you define the same root cause？
According to this standard, all problems caused by map traversal should be the same root cause, and all problems caused by mathematical calculations should be the same root cause?

**Comment by WangSecurity** [comment]
> How do you define the same root cause？
According to this standard, all problems caused by map traversal should be the same root cause, and all problems caused by mathematical calculations should be the same root cause?

I defined the root cause of this issue [here](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2296241108) and [here](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2291343224). I never said that root cause is just "map traversal", I gave the exact issue that is addressed in both reports. The problem is that both reports explain 2 different scenarios but of the same issue. 

I see you say that the root cause of #91 is different [here](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2295444702). But, #91 exactly states `The problem is that if the element in activeTopics does not start at 0, IterateRaw will return less data than the number of pageLimit. Suppose the elements in activeTopics are 20 to 100, startKey is 0, pageLimit is 10, IterateRaw returns a null value`, i.e. not when `activeTopics` is 0 as you say. 

Hence, I believe these 2 issues are the same and I don't see an explanation proving the opposite. The decision remains the same, planning to accept the escalation and duplicate #91 with #60.

**Comment by zhaojio** [comment]
As for the criteria for judging, I have a question:
if there are 2 reports for the same function, using different attack methods and causing different impact, should they be duplicated?

**Comment by WangSecurity** [comment]
If they come from the very same root cause, then I believe yes, they should be considered duplicates. I believe the duplication rules are clear chere:
> The duplication rules assume we have a "target issue", and the "potential duplicate" of that issue needs to meet the following requirements to be considered a duplicate.
Identify the root cause
Identify at least a Medium impact
Identify a valid attack path or vulnerability path
Fulfills other submission quality requirements (e.g. provides a PoC for categories that require one)
Only when the "potential duplicate" meets all four requirements will the "potential duplicate" be duplicated with the "target issue", and all duplicates will be awarded the highest severity identified among the duplicates.

The attack path and the impact are not required to be the same in each report, otherwise, you could submit an infinite amount of reports that come from the same issue but have different attack vectors, which I believe is not the correct way.

**Comment by zhaojio** [comment]
> If they come from the very same root cause, then I believe yes, they should be considered duplicates. I believe the duplication rules are clear chere:
> 
> > The duplication rules assume we have a "target issue", and the "potential duplicate" of that issue needs to meet the following requirements to be considered a duplicate.
> > Identify the root cause
> > Identify at least a Medium impact
> > Identify a valid attack path or vulnerability path
> > Fulfills other submission quality requirements (e.g. provides a PoC for categories that require one)
> > Only when the "potential duplicate" meets all four requirements will the "potential duplicate" be duplicated with the "target issue", and all duplicates will be awarded the highest severity identified among the duplicates.
> 
> The attack path and the impact are not required to be the same in each report, otherwise, you could submit an infinite amount of reports that come from the same issue but have different attack vectors, which I believe is not the correct way.

This rule defines duplicate requirements, 
Now the situation is how do we define whether two issues are the same issue,
The same function, the attack method is different, the impact is different, should be different issue?

**Comment by WangSecurity** [comment]
> The same function, the attack method is different, the impact is different, should be different issue?

I’ve already answered this question in the previous comment, [this comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2297234277), [this comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2296933271).

The decision remains.

**Comment by zhaojio** [comment]
> > The same function, the attack method is different, the impact is different, should be different issue?
> 
> I’ve already answered this question in the previous comment, [this comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2297234277), [this comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2296933271).
> 
> The decision remains.

We can discuss the specific issues in 60 and 91 later.

First of all, we need to figure out how we can determine that the two issues are the same issue. I don't understand why different attack paths, different impact, why should they be the same issue.
What is the `same root cause`.

**Comment by WangSecurity** [comment]
If you have questions about the rules, it’s better to discuss them in Discord and not here. Feel free to DM me. The root cause definition you can find inside the [Glossary](https://docs.sherlock.xyz/audits/judging/judging#xi.-glossary) in our rules.

The decision remains the same.

**Comment by zhaojio** [comment]
> I did not find this issue on my own, I only saw it being fixed on the main repository in this [PR](https://github.com/allora-network/allora-chain/pull/406).

The problem in #60 is that the page data obtained by `GetIdsOfActiveTopics` is incomplete,
There is no loss, and the function `SafeApplyFuncOnAllActiveEpochEndingTopics` from the previous layer continues iterating over the remaining topics according to pageNumber(maxTopicPages).
Suppose an administrator has set up `EndBlocker` to handle 10,000 Topics at once(topicPageLimit* maxTopicPages = 10000)
But the fact that there were only 5000 activeTopics didn't really matter because all 5000 activeTopics were processed.
This only causes problems if topicPageLimit* maxTopicPages < 5000. There are some `activeTopics` that are not addressed, but administrators can change the parameters to avoid this problem.
> (External) Admin trust assumptions: When a function is access restricted, only values for specific function variables mentioned in the README can be taken into account when identifying an attack path.
If no values are provided, the (external) admin is trusted to use values that will not cause any issues.
Note: if the attack path is possible with any possible value, it will be a valid issue.

So #60 should not be High, but #91 is High, and the attacker will cause all the topics to be unprocessed, and cannot be avoided

**Comment by imsrybr0** [comment]
Hi @zhaojio,

* #60 : describes how the returned data is incomplete. Why? Because the iteration assumes IDs are consecutive.
* #91 : describes how the returned data is empty. Why ? Because the iteration assumes IDs are consecutive.

Empty is a specific case of Incomplete, both are caused by the same root cause.

If you check PoC 1 and PoC 2, nothing changed besides the IDs that are activated :
* PoC 1  : 50, 100, 150, 200, 250, ... are activated. Only 50, 100, 150, 200 are returned for the first page with a limit of 200. 
* PoC 2 : 101, 102, ..., 200 are activated. Nothing is returned for the first page with a limit of 100.

That is because GetIdsOfActiveTopics loops sequentially from start to page limit (.i.e start, start + 1, start + 2 , start + 3, ..., start + page limit) to get active topics assuming that :
* Their IDs are consecutive.
* That between start and start + page limit, there is page limit number of activated topics.

**Comment by WangSecurity** [comment]
@imsrybr0 thank you for this extensive explanation and I believe it’s correct. That’s the reason I believe two reports represent the same issue, but different scenarios.

Hence, the decision remains the same, accept the escalation and duplicate #91 with #60

**Comment by zhaojio** [comment]
Even if they're the same root cause,  
The duplication rules is: 
> Identify at least a Medium impact
> Identify a valid attack path or vulnerability path

If all the topics are processed(https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2298071344), What is the impact?  

#91 It clearly illustrates the impact of `the same root cause`, It's not in the other reports.

**Comment by imsrybr0** [comment]
Hi @zhaojio ,

> If all the topics are processed, What is the impact?

This is not necessarily true, it will depend on the activated topic IDs and the maximum number of pages. For example with the default values (100, 100), only active topics with IDs  below 10000 will be processed.

> #91 It clearly illustrates the impact of the same root cause, It's not in the other reports.

What other reports (I didn't check all of them) do not clearly describe is how, in the specific case where nothing is returned for a page (.i.e not active IDs below the page limit), the processing will stop even if there are active topics with consecutive IDs in the next pages.

But ultimately, both describe the same root cause and different vulnerability paths that lead to same end result : incomplete topic processing impacting topics weights updates and revenue.

**Comment by zhaojio** [comment]
>  it will depend on the activated topic IDs and the maximum number of pages.

The prerequisite for `incomplete topic processing` is topicPageLimit* maxTopicPages < activeTopicsNumber , it can set by admin:

> (External) Admin trust assumptions: When a function is access restricted, only values for specific function variables mentioned in the README can be taken into account when identifying an attack path.
If no values are provided, the (external) admin is trusted to use values that will not cause any issues.
Note: if the attack path is possible with any possible value, it will be a valid issue.

so #60 and this report are invalid (medium at most):

This has been stated in my comments above. (https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2298071344)

**Comment by imsrybr0** [comment]
> The prerequisite for incomplete topic processing is topicPageLimit* maxTopicPages < activeTopicsNumber , it can set by admin:

That is again wrong, it is not active topics number that matters, it's their IDs.

Taking again your example as a base : 

* If topicPageLimit * maxTopicPages = 10000
* And there are 5000 active topics
* But there is only one active topic per page ({0, 100}, {100, 200}, {200, 300}, ..., {9900, 10000}), say 50, 150, 250, ..., 9950
* And the other 4900 active topic IDs are above 10000.
* Then only 100 topics will be processed.

The argument that the admin can set those values to safe values is wrong too because there is no guarantee that for the desired number of active topics, their IDs will always all be within the range 0, topicPageLimit * maxTopicPages.

Not to mention it can also invalidate #91 if one can say that the admin can always set a topicPageLimit to match the first active topic IDs.

This is my last comment, I'll accept any decision @WangSecurity takes on this escalation.

Thanks

**Comment by zhaojio** [comment]
> And there are 5000 active topics
> But there is only one active topic per page ({0, 100}, {100, 200}, {200, 300}, ..., {9900, 10000}), say 50, 150, 250, ..., 9950

is only one active topic per page , it not 5000 active topics, it 100 active topics,
In this case, 100 active topics are processed and there is no `incomplete topic processing`.

#91 discusses the case where the `GetIdsOfActiveTopics` function return null.

**Comment by WangSecurity** [comment]
I see the arguments from @zhaojio that indeed the admin can partially mitigate this problem, but as I understand it can still arise. Hence, the following should apply:
> Note: if the attack path is possible with any possible value, it will be a valid issue

I agree that this decreases the severity and indeed medium is more appropriate. But, @imsrybr0 is also correct that these admin assumptions also apply to #91:
> Not to mention it can also invalidate https://github.com/sherlock-audit/2024-06-allora-judging/issues/91 if one can say that the admin can always set a topicPageLimit to match the first active topic IDs.

Hence, I believe the medium is more appropriate for this issue. The decision to duplicate #91 with #60 remains, but I'll decrease the severity of the entire family to medium. Planning to accept the escalation.

**Comment by imsrybr0** [comment]
Hi @WangSecurity, please keep in mind that there is a cost associated with that workaround. High values can open up the chain to slow down / halting issues since this processing is done in the EndBlocker.

**Comment by zhaojio** [comment]
> Not to mention it can also invalidate https://github.com/sherlock-audit/2024-06-allora-judging/issues/91 if one can say that the admin can always set a topicPageLimit to match the first active topic IDs.

it not true
If PageLimit is 100, an attacker can make `GetIdsOfActiveTopics` return null simply by creating 100 inactive Topics. #91 
Even with PageLimit 1000, an attacker can still do this, and the code's comment says: `1000 is excessive for the topic query`.
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/module/rewards/topic_rewards.go#L206

#60 and this report just says that in one page activeTopics return incomplete. But on the next page will be processed again, so,  they are invalid.
`incomplete topic processing` occurs only if `GetIdsOfActiveTopics` returns empty, but #60 and this report do not make that clear.

#91 is High severity, #60 and this report is not.

**Comment by imsrybr0** [comment]
>it not true

Yet, that's what you suggested to circumvent the first scenario.

> If PageLimit is 100, an attacker can make GetIdsOfActiveTopics return null simply by creating 100 inactive Topics. https://github.com/sherlock-audit/2024-06-allora-judging/issues/91
Even with PageLimit 1000, an attacker can still do this, and the code's comment says: 1000 is excessive for the topic query.

An attacker can trigger the second scenario faster, but they have to pay the registration fee for each topic and cannot prevent those topics from becoming active since reputer registration, funding and staking are still possible for those topics.

> incomplete topic processing occurs only if GetIdsOfActiveTopics returns empty

Please go through PoC 1 and the example in this [comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2299018764) again (there are 5000 active topics : 100 active topics with IDs between 0 and 10000 and 4900 active topics with IDs above 10000).

> but https://github.com/sherlock-audit/2024-06-allora-judging/issues/60 and this report do not make that clear.

Please check PoC 2 and the Impact section of this report again.

**Comment by zhaojio** [comment]
> > it not true
> 
> Yet, that's what you suggested to circumvent the first scenario.
> 
> > If PageLimit is 100, an attacker can make GetIdsOfActiveTopics return null simply by creating 100 inactive Topics. #91
> > Even with PageLimit 1000, an attacker can still do this, and the code's comment says: 1000 is excessive for the topic query.
> 
> An attacker can trigger the second scenario faster, but they have to pay the registration fee for each topic and cannot prevent those topics from becoming active since reputer registration, funding and staking are still possible for those topics.
> 
> > incomplete topic processing occurs only if GetIdsOfActiveTopics returns empty
> 
> Please go through PoC 1 and the example in this [comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2299018764) again (there are 5000 active topics : 100 active topics with IDs between 0 and 10000 and 4900 active topics with IDs above 10000).
> 
> > but #60 and this report do not make that clear.
> 
> Please check PoC 2 and the Impact section of this report again.

1. Creating a topic requires payment, activating a topic requires staking, but why would anyone else give an attacker a spam topic staking
2. Although PoC 2 illustrates returns null, but did not say `SafeApplyFuncOnAllActiveEpochEndingTopics` in outer loop will terminate.

**Comment by imsrybr0** [comment]
> 1. Creating a topic requires payment, activating a topic requires staking, but why would anyone else give an attacker a spam topic staking

There is no incentive to activate the attacker's spam topics, I just outlined that it was still possible to activate them.

> 2. Although PoC 2 illustrates returns null, but did not say SafeApplyFuncOnAllActiveEpochEndingTopics in outer loop will terminate.

Please check the SafeApplyFuncOnAllActiveEpochEndingTopics code snippet 

> // <==== Audit : If all active topics IDs are above {topicPageLimit}, topicsActive == nil will be satisfied here as shown in PoC2

**Comment by zhaojio** [comment]
> > 1. Creating a topic requires payment, activating a topic requires staking, but why would anyone else give an attacker a spam topic staking
> 
> There is no incentive to activate the attacker's spam topics, I just outlined that it was still possible to activate them.
> 
> > 2. Although PoC 2 illustrates returns null, but did not say SafeApplyFuncOnAllActiveEpochEndingTopics in outer loop will terminate.
> 
> Please check the SafeApplyFuncOnAllActiveEpochEndingTopics code snippet 
> 
> > // <==== Audit : If all active topics IDs are above {topicPageLimit}, topicsActive == nil will be satisfied here as shown in PoC2

I'm sorry I didn't notice the note in your report.
I think your report should be correct, but #60 doesn't make that clear.

**Comment by zhaojio** [comment]
The cost of the attack depends on the benefits the attacker can gain, if the attacker can disable the system, the attacker is motivated to attack.
In addition, there does not appear to be any mention of attacks in this report.

**Comment by imsrybr0** [comment]
> I'm sorry I didn't notice the note in your report.
I think your report should be correct, but #60 doesn't make that clear.

No worries, all good.

> The cost of the attack depends on the benefits the attacker can gain, if the attacker can disable the system, the attacker is motivated to attack.
In addition, there does not appear to be any mention of attacks in this report.

Curious to know your point of view on the following situations :

* At chain launch, while there are no active topics, the attacker triggers scenario 2 and spam creates pageLimit number of topics. Topics processing is blocked and users are not incentivized to create new topics, fund, stake.
* The chain launches, users create topics, fund and stake normal and after some time an attacker spam creates pageLimit number of topics when conditions are favorable (.i.e when they can create pageLimit consecutive topics that can trigger scenario 2).
* No attacker is involved, the chain launches, users create topics, fund and stake normally. Scenario 1 or 2 happen naturally after some time as topic activates and deactivate.

**Comment by zhaojio** [comment]
> > I'm sorry I didn't notice the note in your report.
> I think your report should be correct, but #60 doesn't make that clear.
> 
> No worries, all good.
> 
> > The cost of the attack depends on the benefits the attacker can gain, if the attacker can disable the system, the attacker is motivated to attack.
> In addition, there does not appear to be any mention of attacks in this report.
> 
> Curious to know your point of view on the following situations :
> 
> * At chain launch, while there are no active topics, the attacker triggers scenario 2 and spam creates pageLimit number of topics. Topics processing is blocked and users are not incentivized to create new topics, fund, stake.
> * The chain launches, users create topics, fund and stake normal and after some time an attacker spam creates pageLimit number of topics when conditions are favorable (.i.e when they can create pageLimit consecutive topics that can trigger scenario 2).
> * No attacker is involved, the chain launches, users create topics, fund and stake normally. Scenario 1 or 2 happen naturally after some time as topic activates and deactivate.

Both are possible. Your report fits the last scenario.

**Comment by WangSecurity** [comment]
Based on [this](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2299841216) comment I indeed agree that high severity for #91 and this report is appropriate, cause the attack is possible with no extensive limitations (as I understand) and can be executed with any admin values.

But, still I believe all are the same family with #60. Hence, the severity is chosen based on the highest severity found among duplicates. This and #91 have found high severity, thus the entire family will be high severity. Planning to accept the escalation and duplicate #91 with #60.

**Comment by zhaojio** [comment]
> Based on [this](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115#issuecomment-2299841216) comment I indeed agree that high severity for #91 and this report is appropriate, cause the attack is possible with no extensive limitations (as I understand) and can be executed with any admin values.
> 
> But, still I believe all are the same family with #60. Hence, the severity is chosen based on the highest severity found among duplicates. This and #91 have found high severity, thus the entire family will be high severity. Planning to accept the escalation and duplicate #91 with #60.

https://github.com/sherlock-audit/2024-06-allora-judging/issues/60 and this report just says that in one page activeTopics return incomplete. But on the next page will be processed again, so it's invalid.

The duplication rules is:
> Identify at least a Medium impact
> Identify a valid attack path or vulnerability path

Also, there is no valid attack path or vulnerability path in #60

**Comment by WangSecurity** [comment]
Hm, about the vulnerability path I disagree and report has it explaining in what situation the bug will happen.

But, indeed the report doesn’t have medium severity impact. It shows a broken functionality, but the only impact is that instead of calling the function once, you have to call it several times.

About this report, I believe it has a medium impact:
> No active topics will be processed for topic rewards if there are no active topics with an ID below the DefaultPageLimit

This can be partially mitigated by the admin, but as I understand this issue will regularly come up, resulting in a loss of funds. Correct me if it’s wrong. This report also has a valid attack path in a form of POC.

Another duplicate (#73) is sufficient duplicate. Planning to accept the escalation, make #91 the main report and others (this and #73) duplicates with High severity.

**Comment by WangSecurity** [comment]
Hm, about the vulnerability path in https://github.com/sherlock-audit/2024-06-allora-judging/issues/60 I disagree and report has it explaining in what situation the bug will happen.

But, indeed the report doesn’t have medium severity impact. It shows a broken functionality, but the only impact is that instead of calling the function once, you have to call it several times.

About this report, I believe it has a medium impact:
> No active topics will be processed for topic rewards if there are no active topics with an ID below the DefaultPageLimit

This is almost the same impact as in the #91, but without the attack part. Correct me if it’s wrong, but I believe it’s medium severity. This report also has a valid attack path in a form of POC.

Another duplicate (https://github.com/sherlock-audit/2024-06-allora-judging/issues/73) is a sufficient duplicate. Planning to accept the escalation, make https://github.com/sherlock-audit/2024-06-allora-judging/issues/91 the main report and others (this and https://github.com/sherlock-audit/2024-06-allora-judging/issues/73) duplicates with High severity.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #91

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imsrybr0](https://github.com/sherlock-audit/2024-06-allora-judging/issues/115/#issuecomment-2277711302): accepted
